module.exports = {
  docs: [
    'about-tuyaopen',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Environment Setup',
          collapsed: false,
          items: [
            'quick_start/windows-enviroment-setup',
            'quick_start/linux-enviroment-setup',
            'quick_start/mac-enviroment-setup',
          ],
        },
        {
          type: 'category',
          label: 'Other Tools',
          collapsed: true,
          items: [
            'quick_start/flashing-with-windows-graphical-interface',
            'quick_start/flashing-with-command-line-interface',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'New Hardware Support',
      collapsed: true,
      items: ['new_hardware/adding-new-chip-platform-support', 'new_hardware/adding-new-board-support'],
    },
    // {
    //   type: 'category',
    //   label: 'Examples',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'examples', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Application Demos',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'applications', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },

    // {
    //   type: 'category',
    //   label: 'Peripherals',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'peripherals', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'TKL Kernal Layer APIs',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'tkl-api', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'FAQs',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'faq', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'contribute',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'contribute_guide', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
  ],
}
