module.exports = {
  docs: [
    {
      type: 'category',
      label: 'About TuyaOpen',
      items: ['about-tuyaopen'],
    },
    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   collapsed: false,
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Installation and Deployment',
    //       collapsed: false,
    //       items: [
    //         {
    //           type: 'autogenerated',
    //           dirName: 'quick_start', // Generate sidebar slice from docs/tutorials/easy
    //         },
    //         {
    //           type: 'autogenerated',
    //           dirName: 'tos_guide', // Generate sidebar slice from docs/tutorials/easy
    //         },
    //         {
    //           type: 'link',
    //           label: 'Supported Releases',
    //           href: '/supported-releases',
    //         },
    //       ],
    //     },
    //   ],
    // },

    // {
    //   type: 'category',
    //   label: 'New Hardware Support',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Support New MCU Platform',
    //       collapsed: true,
    //       items: [
    //         {
    //           type: 'autogenerated',
    //           dirName: 'new_platform',
    //         },
    //       ],
    //     },
    //     {
    //       type: 'category',
    //       label: 'Support New Board',
    //       collapsed: true,
    //       items: [
    //         {
    //           type: 'autogenerated',
    //           dirName: 'new_board',
    //         },
    //       ],
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Examples',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'examples', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Application Demos',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'applications', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },

    // {
    //   type: 'category',
    //   label: 'Peripherals',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'peripherals', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'TKL Kernal Layer APIs',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'tkl-api', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'FAQs',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'faq', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'contribute',
    //   collapsed: true,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'contribute_guide', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },
  ],
}
